---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lida-sec
  namespace: lida
spec:
  encryptedData:
    OPENAI_API_KEY: AgCxDCMUAhA/58/FjOyhhc2gOiG/4lKc12xKGLzrfwHnHAJskOZrx7Ssdhzc6VsW0UzKi0Z/yM9VxMRvrH6WGanmbB8J84Z/GrJjSgp+eJu8mOi7guAQYkCC4gsvyg7ahGvoxV641V2zwh/jI4pa0NKihfJJ99LmDtIe+tZfHTtK9GAgZtWdHbUYg7m/lWq+y36OrfKG0wnLsGMmNePxH5HvKSuqT865SeOuSS1dnCRsnPKB6FdXglXlVCZLAukkRVIpv/4PQ243ePv8AKktTmNjfBtg0GAdp/Jqp2L6w3u8jYfKR7m7ARdx48UokIQEcYejj4K9TNvMvbhWeyJGxWImXElbuwG2xbnUtpGNY3iQbQM0OP0m/xP42B9Z5n9cE3RB0RyeEMt3D1OsTQxresNol8dX+KF3Mx0TLtoiI1Qy6wZFYS44l8oClRVb2t9sevpDTWtB81KJDKaM8e1UQQjeE6DFBOpp0dPA0qkMHWAsNg8k6elOE1sQd7zI/oLlDwGnyOYNMDzGtF+x3V7EyuseVdyWAis78owcOeZAFjRu4tZW9paMHQMM08RM+Wlq1iR0kLCvEhf/JSh3V9lttfrqV2L+owxIjMH/L8+zZ2W987sMvE/7FBWeeEfxbiGidl2Bbh5TEfvWMyzrdWkMxhKoYb85Xr5UCtxZO50jaEhy6iEyNbn7B+HyIVkd1PqhTofjIMdPCMFsvAlEHCVDaP3yk/Xcq7N2euTnDZgLd6L2H3IXyejNLyGs2/UqGcy/U1fj4kc=
  template:
    metadata:
      creationTimestamp: null
      name: lida-sec
      namespace: lida
    type: Opaque
