name: Build and push Lida
run-name: "${{ github.event.head_commit.message || 'No commit message' }} -- <${{ github.ref_name }}> by @${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/*.md'
      - 'k8s/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  call-portainer-webhook:
    name: Deploy to portainer
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Call Portainer webhook
        run: |
          WEBHOOK_URL=${{ secrets.PORTAINER_WEBHOOK }}

          curl -X POST --max-time 60 --fail --show-error --silent -w "%{http_code}" "$WEBHOOK_URL"
